include ../../ThirdParty/PSCommon/BuildSystem/CommonDefs.mak

BIN_DIR = ../../Bin

INC_DIRS = \
	../../Include \
	../Common

SRC_FILES = *.cpp

USED_LIBS += OpenNI2

EXE_NAME = Simple_read_sample_modified

CFLAGS += -Wall

ADDS = -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_stitching

include ../../ThirdParty/PSCommon/BuildSystem/CommonCppMakefile
